remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
url: "https://doc.ghostify.site"
baseurl: ""
social_image: /assets/preview.png
description: "Ghostify est une plateforme multi-service de création d'articles, de CV et de conversion de documents | Ghostify is a multi-service platform for creating articles, resumes and document conversion"
